name: IG handbook CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [14.x, 16.x]

    steps:
    - name: Check out project
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm ci

    - name: Run test script
      run: npm test

    - name: Build production website
      run: npm run build

    - name: Upload artifact
      if: matrix.os == 'ubuntu-latest' && matrix.node == '16.x'
      uses: actions/upload-artifact@v2
      with:
        name: website
        path: |
          ./static.json
          ./public/
        retention-days: 7

  deploy:
    if: github.event_name == 'push' && success()
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        id: download
        with:
          name: website
          path: ~/website
      
      - name: Tar artifact
        run: |
          cd ${{ steps.download.outputs.download-path }}
          tar -cf website.tar .

      - name: Deploy to dokku
        env:
          SSH_KEY: ${{ secrets.DOKKU_SSH_KEY }}
        run: |
          cd ${{ steps.download.outputs.download-path }}
          echo "$SSH_KEY" > id_rsa
          cat ./website.tar | ssh -i ./id_rsa dokku@igpolytech.fr tar:in handbook
